# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cleaning Folders
      run: mvn clean -f pom.xml
    
    - name: Deploy with Maven
      run: mvn  deploy -f pom.xml

    - name: Run bash commands to prepare packaging
      run: |
        echo "Changing directory to Target folder"
        cd target
        echo "Downloading helpers for packaging packages."
        curl -LJO https://github.com/jhonesto/files/raw/main/comps-pkg/jar-in-jar-loader.zip
        curl -LJO https://github.com/jhonesto/files/raw/main/comps-pkg/GEN_MANIFEST.sh
        curl -LJO https://github.com/jhonesto/files/raw/main/comps-pkg/NORMALIZE.sh
        mv GEN_MANIFEST.sh NORMALIZE.sh libs/
        echo "Unzip jar-in-jar-loader.zip"
        unzip -d libs/ jar-in-jar-loader.zip
        echo "Copying com directory to libs folder"
        cp -r classes/com/ libs/
        echo "Create META-INF directory"
        mkdir libs/META-INF
        echo "Creating MANIFEST.MF"
        cd libs
        MAIN_CLASS=org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader CLASS_PATH=. RSRC_CLASS_PATH=$(echo *.jar) RSRC_MAIN_CLASS=com.comps.text.Client sh GEN_MANIFEST.sh
        echo "Normalizing MANIFEST.MF file."
        cat NORMALIZE.sh
        FILE=MANIFEST.MF sh NORMALIZE.sh
        echo "Moving MANIFEST.MF to META-INF folder"
        mv MANIFEST.MF.new META-INF/MANIFEST.MF
        echo "Removing Helpers and Old MANIFEST"
        rm MANIFEST.MF NORMALIZE.sh GEN_MANIFEST.sh
        echo "Creating a jar file"
        jar cvfm comps-FULL.jar META-INF/MANIFEST.MF .
        ls -lh
